# Generated by Django 3.2.7 on 2021-09-19 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request_Info',
            fields=[
                ('reqid', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('qualification', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('pan', models.CharField(max_length=10, unique=True)),
                ('reqdate', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Response_Info',
            fields=[
                ('resid', models.AutoField(primary_key=True, serialize=False)),
                ('response', models.CharField(max_length=150)),
            ],
        ),
    ]
