# Generated by Django 3.2.7 on 2021-09-19 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='request_info',
            table='insertdata',
        ),
        migrations.AlterModelTable(
            name='response_info',
            table='dispalydata',
        ),
    ]
